os: linux
dist: trusty
sudo: required

language: node_js
node_js: stable
cache: yarn

branches:
  only: master

script:
  - npm run lint
  - npm run unit

deploy:
  provider: heroku
  api_key:
    secure: ${HEROKU_TOKEN}
  app: backend-starter-kit
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change
