os: linux
dist: trusty
sudo: required

language: node_js
node_js: stable
cache: yarn

branches:
  only: master

# env:
#   matrix:
#     - MODE=lint
#     - MODE=unit

# matrix:
#   include:
#     - env: MODE=docker
#       services: docker
#       install: true
#       cache: docker
#   exclude:
#     - env: MODE=docker
#       cache: yarn

script:
  - npm run lint
  - npm run unit

# after_success:

deploy:
  provider: heroku
  api_key:
    secure: ${HEROKU_TOKEN}
  app: backend-go-demo
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change
