os: linux
dist: trusty
sudo: required

language: node_js
node_js: stable
cache: yarn

branches:
  only: master

# env:
#   matrix:
#     - MODE=lint
#     - MODE=unit

# matrix:
#   include:
#     - env: MODE=docker
#       services: docker
#       install: true
#       cache: docker
#   exclude:
#     - env: MODE=docker
#       cache: yarn

script:
  - npm run lint
  - npm run unit
  # - docker-compose up -d
  # - docker-compose exec app yarn run lint
  # - docker-compose exec app yarn run unit

# after_success:
  # - docker-compose exec app heroku container:login
  # - docker-compose exec app heroku container:push web

deploy:
  provider: heroku
  api_key:
    secure: ${HEROKU_TOKEN}
  app: backend-starter-kit
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change
