os: linux
dist: trusty
sudo: required

language: node_js
node_js: stable
cache: yarn

branches:
  only: master

env:
  matrix:
    - MODE=lint
    - MODE=unit

matrix:
  include:
    - env: MODE=docker
      services: docker
      install: true
      cache: docker
  exclude:
    - env: MODE=docker
      cache: yarn

# before_install: chmod +x scripts/*.sh

before_script:
  - if [[ "$MODE" == "docker" ]]; then docker-compose up -d; fi

script:
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run lint; fi
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run unit; fi
  - if [[ "$MODE" == "lint" ]]; then yarn run lint; fi
  - if [[ "$MODE" == "unit" ]]; then yarn run unit; fi

# after_success:

deploy:
  provider: heroku
  api_key:
    secure: ${HEROKU_TOKEN}
  app: backend-go-demo
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change
