version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/Backend-Starter-Kit

    branches:
      only:
        - master

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Start up containers
          command: docker-compose up -d

      - run:
          name: Build the application
          command: docker-compose exec api yarn build

      - run:
          name: Test the application
          command: docker-compose exec api yarn test

      - run:
          name: Test coverage integration
          command: docker-compose exec api yarn codecov -- --token=${CODECOV_TOKEN}

      - deploy:
          name: Deploy to Heroku
          command: |
            docker login -u="Shyam Chen" -p="${HEROKU_TOKEN}" registry.heroku.com
            docker build -f Dockerfile.prod -t registry.heroku.com/web-go-demo/web .
            docker push registry.heroku.com/web-go-demo/web
