version: '2'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - SECRET=webgo
      - MONGODB_URI=mongodb://web-go-user:web-go-user@ds133961.mlab.com:33961/web-go-demo
      - POSTGRES_URL=postgres://ymuxoegt:ONfBcCQylth3boOdUE2EkcZbC2OAbtcm@tantor.db.elephantsql.com:5432/ymuxoegt
      - REDIS_PORT=17929
      - REDIS_HOST=redis-17929.c1.us-central1-2.gce.cloud.redislabs.com
      - SENTRY_DSN=https://70484e0dda784a1081081ca9c8237792:51b5a95ee1e545efba3aba9103c6193e@sentry.io/236866
    tty: true
