version: '2'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - SECRET=webgo
      - MONGODB_URI=mongodb://web-go-user:web-go-user@ds133961.mlab.com:33961/web-go-demo
      - POSTGRES_URL=postgres://ymuxoegt:ONfBcCQylth3boOdUE2EkcZbC2OAbtcm@tantor.db.elephantsql.com:5432/ymuxoegt
      - REDIS_PORT=17929
      - REDIS_HOST=redis-17929.c1.us-central1-2.gce.cloud.redislabs.com
      # - GOOGLE_ID=xxx
      # - GOOGLE_SECRET=xxx
      # - FACEBOOK_ID=xxx
      # - FACEBOOK_SECRET=xxx
      # - TWITTER_KEY=xxx
      # - TWITTER_SECRET=xxx
    # depends_on:
    #   - mongo
    #   - postgres
    #   - redis
    # volumes:
    #   - ./api:/opt/api
    tty: true

  # mongo:
  #   image: mongo:jessie
  #   ports:
  #     - "27017:27017"

  # postgres:
  #   image: postgres:alpine
  #   ports:
  #     - "5432:5432"

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
